export const data = [
  {
    orderID: 1001,
    customerName: "Stanly MacCorley",
    last_name: "MacCorley",
    email: "smaccorley0@skype.com",
    phone: "none",
    services: "Soup - Campbells - Tomato",
    quoteDate: "4/11/2021",
    price: "$704.28",
    completed: "true"
  },
  {
    orderID: 1002,
    customerName: "Noemi Crallan",
    last_name: "Crallan",
    email: "none",
    phone: "none",
    services: "Chambord Royal",
    quoteDate: "15/10/2021",
    price: "$501.82",
    completed: "true"
  },
  {
    orderID: 1003,
    customerName: "Hart Lissett",
    last_name: "Lissett",
    email: "none",
    phone: "674-554-8399",
    services: "Butter - Pod",
    quoteDate: "4/4/2022",
    price: "$316.18",
    completed: "false"
  },
  {
    orderID: 1004,
    customerName: "Horton Gotobed",
    last_name: "Gotobed",
    email: "none",
    phone: "none",
    services: "Chicken - Base",
    quoteDate: "18/1/2022",
    price: "$403.91",
    completed: "true"
  },
  {
    orderID: 1005,
    customerName: "Hank Rooper",
    last_name: "Rooper",
    email: "hrooper4@liveinternet.ru",
    phone: "475-886-5595",
    services: "Lotus Rootlets - Canned",
    quoteDate: "22/6/2021",
    price: "$946.34",
    completed: "false"
  },
  {
    orderID: 1006,
    customerName: "Emlen Kienlein",
    last_name: "Kienlein",
    email: "ekienlein5@pbs.org",
    phone: "none",
    services: "Puree - Raspberry",
    quoteDate: "20/12/2021",
    price: "$881.38",
    completed: "true"
  },
  {
    orderID: 1007,
    customerName: "Shelli Leinweber",
    last_name: "Leinweber",
    email: "none",
    phone: "268-241-7824",
    services: "Gatorade - Xfactor Berry",
    quoteDate: "13/8/2021",
    price: "$432.28",
    completed: "true"
  },
  {
    orderID: 1008,
    customerName: "Culley Edinboro",
    last_name: "Edinboro",
    email: "cedinboro7@flavors.me",
    phone: "777-115-4137",
    services: "Squash - Pepper",
    quoteDate: "10/8/2021",
    price: "$782.97",
    completed: "false"
  },
  {
    orderID: 1009,
    customerName: "Shannan Spear",
    last_name: "Spear",
    email: "none",
    phone: "none",
    services: "Chicken Giblets",
    quoteDate: "14/9/2021",
    price: "$680.55",
    completed: "false"
  },
  {
    orderID: 1010,
    customerName: "Beverlee Ferne",
    last_name: "Ferne",
    email: "bferne9@people.com.cn",
    phone: "none",
    services: "Sobe - Berry Energy",
    quoteDate: "27/11/2021",
    price: "$801.39",
    completed: "false"
  },
  {
    orderID: 1011,
    customerName: "Hamlin Jull",
    last_name: "Jull",
    email: "hjulla@merriam-webster.com",
    phone: "423-487-8495",
    services: "Ginger - Pickled",
    quoteDate: "24/10/2021",
    price: "$217.80",
    completed: "true"
  },
  {
    orderID: 1012,
    customerName: "Nollie Ireland",
    last_name: "Ireland",
    email: "none",
    phone: "575-147-6179",
    services: "Daikon Radish",
    quoteDate: "16/9/2021",
    price: "$375.97",
    completed: "true"
  },
  {
    orderID: 1013,
    customerName: "Gardie Pluthero",
    last_name: "Pluthero",
    email: "gplutheroc@oracle.com",
    phone: "832-428-8484",
    services: "Pie Filling - Pumpkin",
    quoteDate: "22/1/2022",
    price: "$860.53",
    completed: "false"
  },
  {
    orderID: 1014,
    customerName: "Stephi Dunseath",
    last_name: "Dunseath",
    email: "sdunseathd@fastcompany.com",
    phone: "none",
    services: "Gelatine Leaves - Bulk",
    quoteDate: "22/4/2022",
    price: "$970.73",
    completed: "true"
  },
  {
    orderID: 1015,
    customerName: "Saraann Bromley",
    last_name: "Bromley",
    email: "none",
    phone: "none",
    services: "Fudge - Chocolate Fudge",
    quoteDate: "30/4/2022",
    price: "$19.22",
    completed: "false"
  },
  {
    orderID: 1016,
    customerName: "Sylas Truesdale",
    last_name: "Truesdale",
    email: "struesdalef@pinterest.com",
    phone: "404-596-5476",
    services: "Lamb Tenderloin Nz Fr",
    quoteDate: "13/2/2022",
    price: "$842.73",
    completed: "false"
  },
  {
    orderID: 1017,
    customerName: "Thea Pickerell",
    last_name: "Pickerell",
    email: "none",
    phone: "none",
    services: "Garlic Powder",
    quoteDate: "21/3/2022",
    price: "$381.97",
    completed: "false"
  },
  {
    orderID: 1018,
    customerName: "Sayers Tewnion",
    last_name: "Tewnion",
    email: "stewnionh@ucoz.ru",
    phone: "409-265-4533",
    services: "Cherries - Fresh",
    quoteDate: "31/3/2022",
    price: "$910.41",
    completed: "true"
  },
  {
    orderID: 1019,
    customerName: "Felice Poulgreen",
    last_name: "Poulgreen",
    email: "none",
    phone: "none",
    services: "Muffin Mix - Corn Harvest",
    quoteDate: "23/9/2021",
    price: "$832.17",
    completed: "true"
  },
  {
    orderID: 1020,
    customerName: "Electra Killock",
    last_name: "Killock",
    email: "none",
    phone: "none",
    services: "Wine - Ice Wine",
    quoteDate: "23/11/2021",
    price: "$951.55",
    completed: "false"
  },
  {
    orderID: 1021,
    customerName: "Rasla Skipworth",
    last_name: "Skipworth",
    email: "rskipworthk@vinaora.com",
    phone: "none",
    services: "Lentils - Green, Dry",
    quoteDate: "30/7/2021",
    price: "$226.44",
    completed: "false"
  },
  {
    orderID: 1022,
    customerName: "Leese Jenkison",
    last_name: "Jenkison",
    email: "none",
    phone: "800-483-7864",
    services: "Soup - Campbells",
    quoteDate: "13/9/2021",
    price: "$781.97",
    completed: "false"
  },
  {
    orderID: 1023,
    customerName: "Sarine Bettesworth",
    last_name: "Bettesworth",
    email: "none",
    phone: "none",
    services: "Bread - Pita, Mini",
    quoteDate: "2/8/2021",
    price: "$107.29",
    completed: "false"
  },
  {
    orderID: 1024,
    customerName: "Mollie Klimov",
    last_name: "Klimov",
    email: "mklimovn@booking.com",
    phone: "none",
    services: "Ecolab Digiclean Mild Fm",
    quoteDate: "22/11/2021",
    price: "$432.05",
    completed: "true"
  },
  {
    orderID: 1025,
    customerName: "Ranee Pridden",
    last_name: "Pridden",
    email: "none",
    phone: "none",
    services: "Aspic - Clear",
    quoteDate: "26/2/2022",
    price: "$253.14",
    completed: "false"
  },
  {
    orderID: 1026,
    customerName: "Caren Buten",
    last_name: "Buten",
    email: "cbutenp@domainmarket.com",
    phone: "883-625-7247",
    services: "Cut Wakame - Hanawakaba",
    quoteDate: "2/8/2021",
    price: "$28.26",
    completed: "true"
  },
  {
    orderID: 1027,
    customerName: "Rab Kobieriecki",
    last_name: "Kobieriecki",
    email: "rkobierieckiq@vk.com",
    phone: "157-394-7839",
    services: "Napkin - Dinner, White",
    quoteDate: "23/9/2021",
    price: "$458.78",
    completed: "true"
  },
  {
    orderID: 1028,
    customerName: "Keir Dooney",
    last_name: "Dooney",
    email: "kdooneyr@histats.com",
    phone: "none",
    services: "Onions - White",
    quoteDate: "18/7/2021",
    price: "$221.39",
    completed: "false"
  },
  {
    orderID: 1029,
    customerName: "Ad Lorman",
    last_name: "Lorman",
    email: "alormans@arstechnica.com",
    phone: "469-719-1732",
    services: "Snapple - Mango Maddness",
    quoteDate: "18/6/2021",
    price: "$765.73",
    completed: "false"
  },
  {
    orderID: 1030,
    customerName: "Danya Balthasar",
    last_name: "Balthasar",
    email: "none",
    phone: "none",
    services: "Juice - Apple, 341 Ml",
    quoteDate: "9/6/2021",
    price: "$49.66",
    completed: "true"
  },
  {
    orderID: 1031,
    customerName: "Dorella Manketell",
    last_name: "Manketell",
    email: "none",
    phone: "739-363-6641",
    services: "Salt - Table",
    quoteDate: "24/5/2022",
    price: "$347.48",
    completed: "true"
  },
  {
    orderID: 1032,
    customerName: "Brenda Ribeiro",
    last_name: "Ribeiro",
    email: "bribeirov@businessweek.com",
    phone: "none",
    services: "Tarts Assorted",
    quoteDate: "6/1/2022",
    price: "$31.38",
    completed: "true"
  },
  {
    orderID: 1033,
    customerName: "Emilie Raigatt",
    last_name: "Raigatt",
    email: "eraigattw@gmpg.org",
    phone: "662-327-7298",
    services: "Juice - Tomato, 10 Oz",
    quoteDate: "27/2/2022",
    price: "$990.33",
    completed: "true"
  },
  {
    orderID: 1034,
    customerName: "Eduardo Birkinshaw",
    last_name: "Birkinshaw",
    email: "none",
    phone: "none",
    services: "Bread - Italian Roll With Herbs",
    quoteDate: "5/9/2021",
    price: "$464.13",
    completed: "true"
  },
  {
    orderID: 1035,
    customerName: "Chariot Wadwell",
    last_name: "Wadwell",
    email: "none",
    phone: "none",
    services: "Cheese - Romano, Grated",
    quoteDate: "23/3/2022",
    price: "$694.94",
    completed: "true"
  },
  {
    orderID: 1036,
    customerName: "Blondelle Bidmead",
    last_name: "Bidmead",
    email: "none",
    phone: "140-610-4378",
    services: "Pail For Lid 1537",
    quoteDate: "15/5/2022",
    price: "$137.54",
    completed: "true"
  },
  {
    orderID: 1037,
    customerName: "Hedwiga Bickle",
    last_name: "Bickle",
    email: "hbickle10@slashdot.org",
    phone: "none",
    services: "Nut - Walnut, Pieces",
    quoteDate: "28/4/2022",
    price: "$600.16",
    completed: "false"
  },
  {
    orderID: 1038,
    customerName: "Tobie Lillicrop",
    last_name: "Lillicrop",
    email: "none",
    phone: "820-618-3818",
    services: "Potato - Sweet",
    quoteDate: "18/2/2022",
    price: "$916.43",
    completed: "false"
  },
  {
    orderID: 1039,
    customerName: "Allard Vooght",
    last_name: "Vooght",
    email: "avooght12@arstechnica.com",
    phone: "581-246-6782",
    services: "Pastry - Carrot Muffin - Mini",
    quoteDate: "12/7/2021",
    price: "$803.26",
    completed: "true"
  },
  {
    orderID: 1040,
    customerName: "Demetris Sandham",
    last_name: "Sandham",
    email: "none",
    phone: "none",
    services: "Versatainer Nc - 8288",
    quoteDate: "13/3/2022",
    price: "$924.06",
    completed: "false"
  },
  {
    orderID: 1041,
    customerName: "Aland Segges",
    last_name: "Segges",
    email: "asegges14@cmu.edu",
    phone: "none",
    services: "Bag - Bread, White, Plain",
    quoteDate: "2/3/2022",
    price: "$366.91",
    completed: "true"
  },
  {
    orderID: 1042,
    customerName: "Karry Nussii",
    last_name: "Nussii",
    email: "none",
    phone: "none",
    services: "Appetizer - Assorted Box",
    quoteDate: "28/10/2021",
    price: "$98.87",
    completed: "false"
  },
  {
    orderID: 1043,
    customerName: "Renae O'Hoolahan",
    last_name: "O'Hoolahan",
    email: "none",
    phone: "none",
    services: "Cookies Almond Hazelnut",
    quoteDate: "9/3/2022",
    price: "$147.46",
    completed: "true"
  },
  {
    orderID: 1044,
    customerName: "Tommie Scholig",
    last_name: "Scholig",
    email: "tscholig17@oaic.gov.au",
    phone: "none",
    services: "Brownies - Two Bite, Chocolate",
    quoteDate: "26/7/2021",
    price: "$57.36",
    completed: "true"
  },
  {
    orderID: 1045,
    customerName: "Yolanthe Linner",
    last_name: "Linner",
    email: "ylinner18@wiley.com",
    phone: "none",
    services: "Potatoes - Instant, Mashed",
    quoteDate: "4/7/2021",
    price: "$406.60",
    completed: "true"
  },
  {
    orderID: 1046,
    customerName: "Wilek Rean",
    last_name: "Rean",
    email: "wrean19@tinypic.com",
    phone: "none",
    services: "Spice - Pepper Portions",
    quoteDate: "31/7/2021",
    price: "$955.02",
    completed: "false"
  },
  {
    orderID: 1047,
    customerName: "Erroll Gullivent",
    last_name: "Gullivent",
    email: "egullivent1a@dailymail.co.uk",
    phone: "993-887-7817",
    services: "Avocado",
    quoteDate: "6/2/2022",
    price: "$50.68",
    completed: "true"
  },
  {
    orderID: 1048,
    customerName: "Tadeas Boadby",
    last_name: "Boadby",
    email: "none",
    phone: "none",
    services: "Pork - Hock And Feet Attached",
    quoteDate: "24/11/2021",
    price: "$356.89",
    completed: "true"
  },
  {
    orderID: 1049,
    customerName: "Pooh Standrin",
    last_name: "Standrin",
    email: "none",
    phone: "none",
    services: "Towel Dispenser",
    quoteDate: "2/4/2022",
    price: "$354.15",
    completed: "true"
  },
  {
    orderID: 1050,
    customerName: "Kimmie Grabham",
    last_name: "Grabham",
    email: "kgrabham1d@biglobe.ne.jp",
    phone: "496-928-3742",
    services: "Soup - Campbells, Cream Of",
    quoteDate: "29/11/2021",
    price: "$710.41",
    completed: "true"
  }
];
